version: '3'

services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: k8s-introduction
      POSTGRES_PASSWORD: db_admin
      POSTGRES_USER: db_admin
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: k8s-introduction
      DB_USERNAME: db_admin
      DB_PASSWORD: db_admin
    depends_on:
      - db
