spring:
  application:
    name: k8s-demo-project
  datasource:
    url: jdbc:postgresql://localhost:5432
    username: db_admin
    password: db_admin
  liquibase:
    url: ${spring.datasource.url}
    default-schema: public
    change-log: classpath:/db/master-changelog.yaml

cursor:
  users:
    default-limit: 10
    default-offset: 0
  posts:
    default-limit: 10
    default-offset: 0
