apiVersion: v1
kind: Secret
metadata:
  name: social-network-secret
type: Opaque
data:
  DB_NAME: azhzLWludHJvZHVjdGlvbgo=
  DB_USERNAME: ZGJfYWRtaW4=
  DB_PASSWORD: ZGJfYWRtaW4=
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: social-network-configmap
data:
  DB_HOST: "postgres"
  DB_PORT: "55432"
---

apiVersion: v1
kind: Service
metadata:
  name: social-network-api-service
spec:
  selector:
    app: social-network-api
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-network-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-network-api
  template:
    metadata:
      labels:
        app: social-network-api
    spec:
      containers:
        - name: social-network-api
          image: kalin748/k8s-demo-project-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: social-network-configmap
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: social-network-configmap
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: social-network-secret
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: social-network-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: social-network-secret
                  key: DB_PASSWORD
