services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      POSTGRES_DB: k8s-introduction
      POSTGRES_PASSWORD: db_admin
      POSTGRES_USER: db_admin
    ports:
      - 5432:5432
